<?php

    function cipher_menu() {
        $items = [];
        $items['cipher'] = [
            'title' => "Shift Cipher",
            'page callback' => 'drupal_get_form',
            'page arguments' => ['cipher_form'],
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        ];
        $items['encrypted_message'] = [
            'title' => "Shift Cipher",
            'page callback' => 'display_cipher',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        ];

        return $items;
    }

    function cipher_form(){
        $form['shift'] = [
            '#title' => 'Shift value',
            '#type' => 'textfield',
            '#element_validate' => ['element_validate_integer_positive'],
            // '#value' => '3',
            '#description' => t('Positive integers only.'),
        ];
        $form['direction'] = [
            '#title' => 'Direction',
            '#type' => 'textfield',
            '#element_validate' => ['element_validate_direction'],
            // '#value' => 'r',
            '#description' => t('Acceptable input(case insensitive): R, L, RIGHT, LEFT'),
        ];
        $form['phrase'] = [
            '#title' => 'Phrase to be encrypted',
            '#type' => 'textfield',
            '#element_validate' => ['element_validate_phrase'],
            // '#value' => 'hello',
            //'#description' => t('something descriptive here'),
        ];

        $form['submit'] = [
            '#type' => 'submit',
            '#value' => 'Encrypt'
        ];

        return $form;
    }
    function element_validate_direction($element){
        $direction = drupal_strtolower($element['#value']);
        if(!($direction == 'l' || $direction == "left" || $direction == "r" || $direction == "right")) {
            form_error($element, t('Direction must be R, L, RIGHT,  or LEFT.'));
        }
    }
    function element_validate_phrase($element){
        $phrase = drupal_strtolower($element['#value']);
        if(preg_match("/[^\w\s\.\,\!\?]/", $phrase)) {
            form_error($element, t('You can only encrypt a phrase containing letters, numbers, and normal punctuation.'));
        }
    }


    function cipher_form_submit($form, &$form_state){
        $alphabet = range("a","z");
        $_SESSION['letters'] = $alphabet;

        $shift = drupal_strtolower($form_state['values']['shift']);
        $direction = drupal_strtolower($form_state['values']['direction']);
        $phrase = drupal_strtolower($form_state['values']['phrase']);

        $_SESSION['shift'] = $shift;
        $_SESSION['direction'] = $direction;
        $_SESSION['phrase'] = $phrase;

        $shift = (int) $shift;
        if($direction == "l" || $direction == "left"){
            $shift *= -1;
            $_SESSION['shift'] = $shift;
        }

        $phrase = str_split($phrase);
        $output = '';
        foreach($phrase as $letter){
            if(preg_match("/[a-z]/",$letter)){
                $output .= $alphabet[abs(array_search($letter, $alphabet) + $shift) % 26];
            } else {
                $output .= $letter;
            }
        }

        $_SESSION['output'] = $output;
        // $_SESSION['output'] = implode($phrase);
        $form_state['redirect'] = 'encrypted_message';
    }

    function display_cipher(){
        // var_dump($_SESSION['alphabet']);
        return "<p>Your encrypted phrase is '" . $_SESSION['output'] . "'</p>
        <ul>
            <li>SHIFT: ".$_SESSION['shift']."</li>
            <li>DIRECTION: ".$_SESSION['direction']."</li>
            <li>PHRASE: ".$_SESSION['phrase']."</li>
        </ul>
        ";
    }
